### ISSUE TITLE
仮想通貨の残高が0になるとゼロ除算エラーが発生する

### ISSUE THREAD

**Issue by mzsm** [ecoopnet/zaif-cli#1]
表題のとおりです。

次のJSONを`zaif-log-parser`に食わせて実行
````
{
  "4773329": {
    "currency_pair": "zaif_jpy",
    "action": "bid",
    "amount": 276.6,
    "price": 2.4399,
    "fee_amount": 0,
    "your_action": "ask",
    "bonus": null,
    "timestamp": "1513828004",
    "comment": ""
  },
  "4771078": {
    "currency_pair": "zaif_jpy",
    "action": "ask",
    "amount": 276.6,
    "price": 2.388,
    "fee_amount": 0,
    "your_action": "bid",
    "bonus": null,
    "timestamp": "1513824845",
    "comment": ""
  }
}
````

次のようなエラーが発生

````
traded: {'currency_pair': 'zaif_jpy', 'action': 'ask', 'amount': 276.6, 'price': 2.388, 'fee_amount': 0, 'your_action': 'bid', 'bonus': None, 'timestamp': '1513824845', 'comment': ''}
{'amount': Decimal('276.6000000000000227373675443'), 'subtotal_jpy': Decimal('660.5208000000000267817767962'), 'unit_price': Decimal('2.387999999999999900524016994'), 'benefit': Decimal('0')}
Traceback (most recent call last):
  File "./bin/zaif-log-parser", line 78, in <module>
    result = functools.reduce(each, sorted(input.items()), {})
  File "./bin/zaif-log-parser", line 60, in each
    unit_price = subtotal_jpy / amount
decimal.DivisionByZero: [<class 'decimal.DivisionByZero'>]
````

**Comment by ecoopnet** [comment]
修正しました👍
